### PR TITLE
Create GitHub action to check pull requests

### PR DESCRIPTION
**Pull request by sonngdev**
# ✨ Codu Pull Request 💻

Codu Logo

## Pull Request details:
- Related issue: #649 
- Add a new GitHub action to run on each Pull request. It will:
  - Run ESLint: `npm run lint`
  - Run Prettier: `npm run prettier` (this command is a breaking change, see below)
  - Run Jest tests: `npm run test:jest`

## Any Breaking changes:
- Previously, running `npm run prettier` will also fix the styling errors detected by Prettier. This command now only checks for errors. To fix them automatically as before, use `npm run prettier:fix`.

## Associated Screenshots:
Each Pull request will have an action like this moving forward.

New action running in each new PR

Click on **Details** to see how each step runs.

The Detail page of the new action

### CODE REVIEW

**Comment by sonngdev** [comment]
## Pending items

Some pending items need further discussion and should be handled after this PR:

### Lint warnings

Currently there are a lot of ESLint warnings. Some easy ones that can be quickly fixed are `@typescript-eslint/consistent-type-imports` and `@typescript-eslint/no-unused-vars` rules. I suggest we make these into `error` instead, otherwise they could easily be missed in future PRs (warnings don't make the lint command fail).

### TypeScript checks

Similarly, there are lots of TS errors, and they make the check fail (that's why I don't include a TS check in this PR). Type fixes can be complex and therefore should have its own PR and discussion.

### Playwright tests

Honestly I don't know enough about Playwright and Prisma to include it in this GH Action at the moment.

**Comment by NiallJoeMaher** [comment]
@thanhsonng this is amazing! I have a PR open with Playwright so between us this should catch most things.

**Review by NiallJoeMaher — APPROVED** [review]
🌮 Fantastic addition!

**Comment by sonngdev** [comment]
@NiallJoeMaher Thanks for merging, it's a pleasure to contribute as always 🚀

**Pull request merged**
