### PR TITLE
Feat/ Course Overview Page

### PR DESCRIPTION
**Pull request by serzhan181**
# ✨ Codu Pull Request 💻

Codu Logo

👉 _**Please remove the below and replace with your own values, leaving the headers where they are.**_ 👈

## Pull Request details:
- Course Overview page (hardcoded for now as requested) 🤜

## Any Breaking changes:
- None

## Associated Screenshots:
изображение
изображение
изображение

_( Welcome file extensions include gifs/png screenshots of your feature in action )_

- None

### CODE REVIEW

**Comment by praveen-quizizz** [comment]
@serzhan181 can you also share mobile/table screenshots for reference and also a good practice to mention the issue name in the PR for tracking and closing issues.

**Comment by sonngdev** [comment]
I think it is easier for users to understand if we start the progress loop from the 12 o'clock position instead of 3 o'clock. What do you think?

**Comment by serzhan181** [comment]
@praveen-quizizz

Did that! I am quite new to open source, sorry if PRs are not clear enough. Also the link to the issue im trying to resolve: https://github.com/codu-code/codu/issues/334

**Comment by pkspyder007** [comment]
Great work @serzhan181 , all looks good can we just move the components out to the `components` folder and use them by importing this will make a little easier to read and modular.

Thank you for the efforts and contributions :)

**Review by NiallJoeMaher — APPROVED** [review]

**Comment by NiallJoeMaher** [comment]
Well done! Thanks for helping out

**Pull request merged**
