### PR TITLE
WIP: Fix social media meta tags

### LINKED ISSUE #151: Article preview doesn't look as intended on LinkedIn and Twitter
## Context

Thank you for the great work on the Writing editor. However, I'm seeing some issues when sharing an article on social media.

## Expected Behavior

- Twitter: The card type should be [Summary card with large image](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image).
- LinkedIn: The image from `og:image` should be used as the article preview.

## Current Behavior

- On Twitter, the preview image is right but it is cropped and can hardly be seen. This is because the card type is Summary.
- On LinkedIn: The first image from the article is used as the article preview, even though `og:image` points to a different image. If an article doesn't include any image, it wouldn't have any preview image.

## Screenshots

Screenshot 2023-02-04 at 9 35 57 a m

Screenshot 2023-02-04 at 9 49 27 a m

Screenshot 2023-02-04 at 9 49 07 a m

## Steps to reproduce

Just try sharing any article on Twitter/LinkedIn

## Additional info

I can take a look at this issue if you assign it to me.

### PR DESCRIPTION
**Pull request by sonngdev**
# ✨ Codu Pull Request 💻

Codu Logo

## Pull Request details:
Related issue: #151 
- [x] Twitter
- [ ] LinkedIn

## Any Breaking changes:
None

## Associated Screenshots:
Issue fixed on Twitter

Screenshot 2023-02-04 at 1 30 32 p m

### CODE REVIEW

**Review by NiallJoeMaher — APPROVED** [review]

**Review by NiallJoeMaher — CHANGES_REQUESTED** [review]
I just saw that you have this in WIP! I'll review again if you add more on top 🦾

**Comment by sonngdev** [comment]
Yes. I will investigate LinkedIn some more. 🔎

**Comment by sonngdev** [comment]
I did some further investigation but couldn't make it work on LinkedIn yet. In the meantime, we can merge this change to at least improve the sharing feature on Twitter first.

Some of my findings:
- Compared with https://jhey.dev/: 
  - Jhey's site also uses an `/og` route to fetch the preview image, so dynamically generated images instead of static images (files that end with .png or .jpeg) are not an issue.
  - I tried adding `<meta name="image" />`, `<meta name="image" property="og:image" />`, `<meta name="og:image" />`, `<meta property="og:image:width" />`, `<meta property="og:image:height" />` like those on his site, didn't work.
- Compared with https://remix.run/blog:
  - This site also uses dynamically generated images.
  - I tried adding `<meta name="twitter:image />` like on this site, didn't work (not surprising, had to try though...)

**Comment by NiallJoeMaher** [comment]
Makes sense! Let's get these changes merged and we can open up a new issue for the LinkedIn issue.

**Review by NiallJoeMaher — APPROVED** [review]

**Pull request merged**
