### PR TITLE
Remove codu logo in pull_request_template.md

### LINKED ISSUE #1017: Remove Codu logo from pull request template
## Context

The pull request template contains a markdown link to the Codu image. 
This image is superfluous and can be removed.

Note : This one should be left for beginners.

## Expected Behavior
This is the offending line of code. Please remove it.
Codu Logo](https://raw.githubusercontent.com/codu-code/codu/develop/public/images/codu-gradient.png)

You will find the "pull_request_template.md" markdown file in the .github folder.

## Screenshots
PR template

### PR DESCRIPTION
**Pull request by ChinoUkaegbu**
# ✨ Codu Pull Request 💻

Codu Logo

## Pull Request details

- Removes the Codu Logo from the PR template
- Closes #1017 

## Any Breaking changes

None

## Associated Screenshots

None

### CODE REVIEW

**Comment by ChinoUkaegbu** [comment]
Unrelated but it might also be a good idea to have a "Closes #issue number" line in the PR template to indicate to contributors to link the related issues

**Comment by NiallJoeMaher** [comment]
> Unrelated but it might also be a good idea to have a "Closes #issue number" line in the PR template to indicate to contributors to link the related issues

Very smart! Want to create an issue with that?

**Review by NiallJoeMaher — APPROVED** [review]
🌮 LGTM!

**Comment by ChinoUkaegbu** [comment]
> > Unrelated but it might also be a good idea to have a "Closes #issue number" line in the PR template to indicate to contributors to link the related issues
> 
> Very smart! Want to create an issue with that?

Sure thing! Created PR #1019

**Pull request merged**
