### PR TITLE
Article Topic addition improvements

### PR DESCRIPTION
**Pull request by JohnAllenTech**
# ✨ Codu Pull Request 💻

Codu Logo

## Pull Request details

- Fixes an issue where the topic helper text wasnt on its own line
- Improves (IMO) the look of tags

## Any Breaking changes

- None

## Associated Screenshots
Before this PR
image

After this PR
image

## Summary by CodeRabbit

- **New Features**
	- Improved tag handling in the `Create` component for enhanced UI/UX, including updated tag mapping and rendering with delete buttons.

### CODE REVIEW

**Comment by JohnAllenTech** [comment]
@NiallJoeMaher reverted the close icon changes. This is just a little bit of rounding around the edges and fixing the text not always being on its own line

**Comment by JohnAllenTech** [comment]
Hey @NiallJoeMaher is this something we want to do or will I close the PR? No hassle if it’s not the way you want to go

**Comment by NiallJoeMaher** [comment]
> Hey @NiallJoeMaher is this something we want to do or will I close the PR? No hassle if it’s not the way you want to go

Yes, could we revert to square for the moment on the corners? Since the input is sharp it looks a bit off. I have brand new designs incoming and it should look much better than what we currently have but yes we want these fixes!

**Review by NiallJoeMaher — CHANGES_REQUESTED** [review]
Revert corners please <3

**Comment by JohnAllenTech** [comment]
> Revert corners please <3

Will do. Excited to see new designs

**Comment by JohnAllenTech** [comment]
@NiallJoeMaher done
image

**Review by NiallJoeMaher — APPROVED** [review]
🌮 🕐

**Pull request merged**
