### PR TITLE
add light and dark mode to the articles [slug].tsx file

### PR DESCRIPTION
**Pull request by Mrst12**
# ✨ Codu Pull Request 💻

Codu Logo

👉 _**Please remove the below and replace with your own values, leaving the headers where they are.**_ 👈

## Pull Request details:
pull request for light and dark mode to be added to the articles [slug}.tsx page.
have added a colour change on the menu for the light section included 2 screenshots one with white one with the new colour going with the rest of the colouring see which one you want in.

## Any Breaking changes:
None

## Associated Screenshots:
    
_( Welcome file extensions include gifs/png screenshots of your feature in action )_

articles-white
articles-grey
articles-hover

### CODE REVIEW

**Comment by Mrst12** [comment]
Im not sure if this is all that is required for this issue could you please confirm as didnt want to change the article in any way in case i was wrong the code on the page seemed to be targeting the side bar, if you want me to change the article itself can you just send a link for the page or is it the same page many thanks
Lisa

**Review by NiallJoeMaher — CHANGES_REQUESTED** [review]
Aha my mistake! The pop up menu should remain the same (since it was designed for light mode and I never got around to the dark version). 

There is a class that wraps all of the articles called `.prose`. 

Any of the classes with `.prose` might need updating. 

You can find it here:

https://github.com/codu-code/codu/blob/develop/styles/globals.css

**Comment by Mrst12** [comment]
So just to clarify the work I did on the [slug].tsx file needs putting back to how it was and work on the new file you sent me sorry just like to get things right 😊

**Comment by NiallJoeMaher** [comment]
> So just to clarify the work I did on the [slug].tsx file needs putting back to how it was and work on the new file you sent me sorry just like to get things right 😊

@Mrst12 yes that's correct!

**Comment by Mrst12** [comment]
Hi @NiallJoeMaher can you help me out please, i have put the [slug].tsx file back to how it was in the original repo no worries about that however in light mode it is showing up the dark colours in the localhost: 3000
articles-reversed
There is also some dark attributes already on the .prose classes in the global css file so can you please clarify what values you want for light  and dark for text, and background also there is a border set in the prose class with dark values so if you can confirm what you want the values to be for light and dark  i can go through and check and change if necessary
Sorry this is my first open source contribution i dont want to get it wrong and my confidence is not that brilliant i am however willing to keep plodding just need a bit of guidance sorry for being a pain 😊

**Comment by NiallJoeMaher** [comment]
Ah it looks like you need to update in both places then. Thats my fault not yours for misreading in the code review. For the menu itself the drop down of options that doesn't need to be updated but this box does.

Then all of the .prose styles should affect the article formatting. How the text and everything is formatted. So just seeing anywhere there is light text and adding in the appropriate light dark modes. 

If you want more specific let me know and I'm more than happy to guide you. Great work so far!

**Comment by Mrst12** [comment]
@NiallJoeMaher no worries so i can revert my [slug].tsx file back to what i did yesterday (not committed the change yet so its simple enough to undo the changes.)
The .prose classes should have the same light and dark values as the [slug].tsx page is this correct 
Thank you

**Comment by NiallJoeMaher** [comment]
Would you show me a screenshot of one of the example articles when you've got a chance (in light and dark mode). Might make more sense if I see it. Because I think I am misunderstanding. 

It's just to make sure the text is visible in both light and dark mode. But maybe a side affect of another PR fixed some of these issues.

**Comment by Mrst12** [comment]
this is the dark mode and light mode with the changes from yesterday to the [slug].tsx file without the dropdown box being affected. The global.css file doesnt seem to alter the text being light on the prose classes am i ok to send the pull request for the box at the side to be merged as then at least i feel i have done something thats right 😊
dark-mode
light-mode

**Comment by Mrst12** [comment]
further down the page in light mode the text is visible without altering any code
light

**Comment by NiallJoeMaher** [comment]
Ah got you! So we need darker text so it's easy to read articles while in light mode. 

So on light mode: 
- The body should have a `gray-800`,
- The titles should be `gray-900`,
- The borders on inline code should be `gray-300`.

The dark mode should keep the same styling as before. 

We use Tailwind, so we should enable this by having a default light mode and dark mode with the dark: prefix.
You can see how this is done here: https://tailwindcss.com/docs/dark-mode

I mocked up what it should look like here: 
Screenshot 2023-10-03 at 13 21 56

**Comment by Mrst12** [comment]
Thats looks better @NiallJoeMaher are you doing this as a separate issue am happy to plod and be assigned it if you are you would just need to let me know which file to change the styles in.
do you want me to send you the pull request later for the side box that i have altered,(screenshot)  cant work on issues now as got to go to harvest festival assembly
heres the screen shot of the articles side as it stands in my code at the minute


update
Just let me know how you want me to proceed sorry feel like i being a right burden

**Comment by NiallJoeMaher** [comment]
Not a burden at all! You are helping. You can split it into two PRs if you like since it will be two different parts of the page. And you'll get two contributuions 🥳

**Comment by Mrst12** [comment]
Will send pull request when kids in bed and tackle the rest tomorrow thank you 😊

**Review by NiallJoeMaher — APPROVED** [review]

**Pull request merged**
