### PR TITLE
Adding Post.likes migration

### PR DESCRIPTION
**Pull request by JohnAllenTech**
# ✨ Codu Pull Request 💻

Codu Logo

## Pull Request details

- Added a migration which sets the new likes column on the post table to the number of likes it has by counting rows in Like table 
- Altered seed script to now have likes created
- Changed previous migration names to be more informative

Theres a small dance you need to do to test this.
1. On develop branch run ```npm run db:migrate``` this will get the DB into the current state it is on dev
2. On this branch run ```npm run db:seed``` this will add the likes that are needed for the DB migration to show its functionality (previous seed script didnt add any likes so all likes would remain 0)
3. On this branch run ```npm run db:migrate```

You should now see the likes column being populated

## Any Breaking changes

- None

## Associated Screenshots

Before
image

After
image

### CODE REVIEW

**Review by NiallJoeMaher — CHANGES_REQUESTED** [review]
Do we need a script for this to migrate the likes count and it's current state?

**Comment by JohnAllenTech** [comment]
@NiallJoeMaher  #872 has this and then #887 will populate the likes column correct with migration 0002

**Comment by NiallJoeMaher** [comment]
@JohnAllenTech so merge this one first then?

**Comment by JohnAllenTech** [comment]
> @JohnAllenTech so merge this one first then? 

Can you give me 15 mins just cleaning up the other and making sure it all plays nice together

**Comment by NiallJoeMaher** [comment]
@JohnAllenTech I'm going for a pint so it'll be tonight before I run the migrations anyway so take your time! ❤️

**Review by NiallJoeMaher — APPROVED** [review]
🌮 👑

**Pull request merged**
