### PR TITLE
Feature onboard developer form b2

### PR DESCRIPTION
**Pull request by John-Paul-Larkin**
## Pull Request details
I was experimenting with prisma migrations on the old branch, so I created a new branch for this PR.

I removed the DeveloperDetails model and added all fields to the User model instead. 
npx prisma migrate dev && npx prisma migrate reset

I removed the splash page so the route is now:
/alpha/additional-details

I left the summary page in for now. 

## Any Breaking changes
NB
I removed @unique from the Membership and RSVP tables. Otherwise, I could not migrate.
I have to go out now, but will try my best to figure this issue later.

## Summary by CodeRabbit

- **New Features**
	- Introduced a comprehensive sign-up process for additional user details, including profile, demographic, work, and education information.
	- Added form validation and submission handling for updating user details.
	- New page component for fetching and displaying user details with authentication support.
	- Implemented predefined options for form fields such as gender, professional status, and level of study.

### CODE REVIEW

**Comment by John-Paul-Larkin** [comment]
This was my first time to reconcile a branch divergence. It was only the prisma file, so I think it should be fine.

**Comment by John-Paul-Larkin** [comment]
>> It was only the prisma file, so I think it should be fine.

Actually, I am really starting to doubt myself, so please check this  to be sure :)

**Comment by NiallJoeMaher** [comment]
> > > It was only the prisma file, so I think it should be fine.
> 
> Actually, I am really starting to doubt myself, so please check this to be sure :)

Don't panic! Let me pull this and make sure it's all good. Might be later before I get it tested.

**Review by NiallJoeMaher — APPROVED** [review]
🌮

**Pull request merged**
