### PR TITLE
remove sst package from json & .gitignore , ss.config.ts delete

### LINKED ISSUE #1027: Remove anything relating to the SST package
Note : This issue will only be assigned to beginners.
If you have previously contributed to open source, or have experience, please filter out the issues tagged with "good first issue" and "beginner friendly".

## Context

SST Serverless stack - is an open-source infrastructure-as-code tool for building on AWS with TypeScript, which allows us to easily manage resources on AWS and handle deployments for JS frameworks.

The project no longer utilises the SST package, so it can be removed from the codebase.

## Expected Behavior

Uninstall the SST package, and remove any references to it.
For instance there is a config file which can be safely deleted:
sst.config.ts 

There is also a script in the package.json which can be deleted
"sst:dev": "sst bind next dev",

It is also referenced in the .gitignore

You can do a search to see if it is referenced anywhere else

## Additional info

Any questions feel free to ask.

### PR DESCRIPTION
**Pull request by dhaneshwaritendle**
# ✨ Codu Pull Request 💻

Fixes #1027 
Remove anything relating to the SST package #1027

## Pull Request details

- npm uninstall sst
- Update package.json: "sst:dev": "sst bind next dev",
-  Remove Config File:  ss.config.ts
- Updated .gitignore 

- Checked for any sst dependencies 
- Tested the application locally no issues

## Any Breaking changes

- 'None'

## Associated Screenshots

- 'None'

### CODE REVIEW

**Comment by John-Paul-Larkin** [comment]
Hello @dhaneshwaritendle 
Thanks very much for this. You are nearly there with your first contribution.
Did you use run the command "npm uninstall sst", or did you manually delete the line   
"sst": "2.40.3"
from the package.json?
I ask because package-lock.json is not included in the diff?
Also the file sst.config.ts does not seem to have been deleted?

**Comment by dhaneshwaritendle** [comment]
> Hello @dhaneshwaritendle Thanks very much for this. You are nearly there with your first contribution. Did you use run the command "npm uninstall sst", or did you manually delete the line "sst": "2.40.3" from the package.json? I ask because package-lock.json is not included in the diff? Also the file sst.config.ts does not seem to have been deleted?

I ran the command npm sst uninstall.
I did delete the file sst.config.ts but I missed commiting the deletion of the file.

**Comment by John-Paul-Larkin** [comment]
Hi dhaneshwaritendle,

If you look at the top here you will see the number of lines modified in this PR is very large. I tested this on my local machine and I believe that something has gone wrong on your end. Consequently, I will close this PR. 
Maybe you can try another one? 

Line count

**Comment by John-Paul-Larkin** [comment]
Hi again dhaneshwaritendle,
It possible the incorrect node version is causing this issue.
Did you run "nvm use"command to ensure you have the correct node version in the .nvmrc file (v18.17.1)
Its probably best that you create a new, up to date branch for this.
Thanks

**Review by NiallJoeMaher — APPROVED** [review]
🌮  Thanks for this! Going to merge this because I need to update a load of dependencies which will fix any issues with this.

**Pull request merged**
