### PR TITLE
Fishamble feature 393 article search picker

### PR DESCRIPTION
**Pull request by John-Paul-Larkin**
# ✨ Codu Pull Request 💻

Codu Logo

## Pull Request details:
- Added a responsive search  bar and date picker to the article section of the site.

I am still trying to figure things out, so you will have to forgive my poor commit history. I originally had a number of separate commits, but ended up doing a reset and combining them into a single one.

The search part was pretty simple, but I used shadcn to implement the date picker, which added 8 packages, including radix ui. It added utility classes for the light/dark mode to the styles/globals.css. Some of these are not strictly necessary, but I left them in, as I was not sure how the light/dark mode will be implemented. It also added a number of custom themes to the tailwind.config.js. I don't know if these will cause conflicts down the line?

This is a learning exercise for me, so I have no issue with scrapping the lot, or going back to make any changes. Feedback, or resources to help me through the contribution process would be greatly appreciated.

## Any Breaking changes:
None

## Associated Screenshots:
    https://www.youtube.com/watch?v=3zhH449joUk

### CODE REVIEW

**Comment by NiallJoeMaher** [comment]
Awesome, thanks! I’ll check this out and go over the code later. My only concern is all of the additional packages that were required for this addition. The logic looks pretty good though!

**Comment by John-Paul-Larkin** [comment]
Yes, I dont know the protocol re adding extra packages. I originally thought to use shadcn, as I had read it was a no install component library, however the calendar component uses react-day-picker and radix ui.

**Comment by NiallJoeMaher** [comment]
Aha I got you! I don't think we need the calendar picker. The more libs we can strip out, the better! 
I don't have clear guidelines on the adding packages stuff yet. I think as a rule of thumb, it's worth a discussion. I'll add it to the contribution guidelines. 🦾 

If you don't mind stripping out the calendar and all the dependencies it adds that would be awesome. If you don't have time let me know and I'll add some changes on top of this branch. 

The video looks great. 👍 Well done! 🥂 Thanks for this!

**Review by NiallJoeMaher — CHANGES_REQUESTED** [review]
Let me know if you can pull out all the calendar work in this one. Great work! I see some conflicts too. If you need a hand let me know. 🦾

**Pull request closed without merging**
