### PR TITLE
Add avatar to the onboarding flow

### LINKED ISSUE #1008: Add avatar to the onboarding flow
Note : This issue will only be assigned to beginners.
If you have previously contributed to open source, or have experience, please filter out the issues tagged with "good first issue" and "beginner friendly".

## Context

On slide one of the additional-details (onboarding form) we want to add an Avatar, similar to how is it is shown on the current settings page.  The avatar is populated through the users Github account
We are using the [Catalyst](https://tailwindui.com/templates/catalyst) component library from tailwind UI.
The Catalyst docs have a section showcasing Avatars.

## Expected Behavior

Currently there are three slides, and they are a fixed height to match each other. 
Slide one already has four fields 'First name', 'Surname', 'Username' and 'Location'.
Slide two only has two fields, 'Gender' and 'Date of birth'.
It might make sense to move the 'Location' and/or 'Username' fields to slide two. 
You can decide which you think looks/works best, just please keep the styles and height consistent across the slides.

## Current Behavior

Current slide one.

Current slide one
Current slide two.
Current slide two

This is the avatar on the settings page

Avatar on settings page

## Additional info

Note: The catalyst components can be found at :

components> ui-components

The onboarding form is found at

app>(app)>alpha>additional-details

Any questions feel free to ask.

Connected issues
#1003
#1004 
#1005 
#1006 
#1008 
#1009
#1011

### PR DESCRIPTION
**Pull request by sahilpatel2712**
# ✨ Codu Pull Request 💻

Fixes #1008 

## Pull Request details

- Add an avatar to the onboarding flow
- Avatar can be changed by the user

## Any Breaking changes

 'None'

## Associated Screenshots
image

### CODE REVIEW

**Comment by John-Paul-Larkin** [comment]
Hey @sahilpatel2712 
Thanks for this PR, however, there are some issues pointed out by code rabbit. Especially around the error handling and file size limit. 
I see this code follows the approach used on the existing Settings page, but there’s definitely room to make some of the same improvements there also.

Also, the alignment of the elements you added are not visually balanced. Again, I realise this code comes directly from the existing settings page, however in this case  the styles should be customised for this form.
"Profile picture", the avatar and "Full Name" should be aligned for a cleaner look. Similarly the "Change avatar" button should be aligned in a cihesive way with the avatar.

Thanks,
JP

**Comment by sahilpatel2712** [comment]
Hi @John-Paul-Larkin 
Thank you for mentioning the avatar alignment issues, I solved those issues in the next commit `9c76adf` , and issues pointed by code Rabit
about validate file type and file size are already done in getUploadUrl method located at folder
https://github.com/codu-code/codu/blob/develop/server/api/router/profile.ts
Please let me know if any further changes are needed.
 
 
 
image

**Review by John-Paul-Larkin — CHANGES_REQUESTED** [review]
Hey @sahilpatel2712 

Thank you for implementing the recent changes.

At this point, the uploadToUrl functionality is being used both on the settings page and the additional-details page. However, the code has started to diverge due to the error handling modifications you introduced.

Given this, it would make sense to refactor the logic into a shared utility function. Could you please extract this logic into a utility function and place it in the utils folder so it can be reused in both places?

Thanks!

**Comment by John-Paul-Larkin** [comment]
Hi @sahilpatel2712 
I think there may be some confusing here. I should have been more explicit with my previous instruction.
I see you have extracted the uploadToUrl function to a util. 
What I meant was that **any** logic shared between the two components should be extracted to a utility function.
In other words the logic you originally copied from the settings component should be in the utility.  
This will ensure the error handling will also be included for the settings page, and any change to it will be implemented for both components.
I hope this makes sense?

**Comment by sahilpatel2712** [comment]
> Hi @sahilpatel2712 I think there may be some confusing here. I should have been more explicit with my previous instruction. I see you have extracted the uploadToUrl function to a util. What I meant was that **any** logic shared between the two components should be extracted to a utility function. In other words the logic you originally copied from the settings component should be in the utility. This will ensure the error handling will also be included for the settings page, and any change to it will be implemented for both components. I hope this makes sense?

that mean I also should move imageChange function logic from both components into util function?

**Comment by John-Paul-Larkin** [comment]
> > Hi @sahilpatel2712 I think there may be so confusing here. I should have been more explicit with my previous instruction. I see you have extracted the uploadToUrl function to a util. What I meant was that **any** logic shared between the two components should be extracted to a utility function. In other words the logic you originally copied from the settings component should be in the utility. This will ensure the error handling will also be included for the settings page, and any change to it will be implemented for both components. I hope this makes sense?
> 
> that mean I also should move imageChange function logic from both components into util function?

Yes, the logic which is shared should be extracted from both and combined into a utility.

**Comment by NiallJoeMaher** [comment]
There is a ton of code duplication, and the design doesn't look as it does on the settings page, so I won't merge this in just yet. It will create more code than needed to maintain. 

- I think the Avatar upload code should be its own component to stop duplicated logic in 2 separate areas.
- Anywhere there is duplicated code, there should be an attempt at reuse. 

Feel free to reopen if you want to tackle it without the copy/pasting.

**Pull request closed without merging**
