### PR TITLE
Dacallaghan/slate editor

### PR DESCRIPTION
**Pull request by xiaoniuniu89**
# ✨ Codu Pull Request 💻

Codu Logo

👉 _**Please remove the below and replace with your own values, leaving the headers where they are.**_ 👈

## Pull Request details:
- Rich text editor. still a number of bugs to iron out, but is stable as is. If we are happy to proceed with this editor then I will make an epic with some bugs that should be fixed for this release of the new editor. If anybody is interested in working on getting this to the finish line, please let me know, I can organise a call and walk people through the code. For the time being, you can see the rendered content from the preview tab in the create/edit page. if you want to see in the blog page you can comment out the markdoc rendered content and uncomment the content rendering the html. 

## Any Breaking changes:

yes , This is not ready for production, it does not take into account making older posts backward compatible yet as we are switching from markdown to dealing with json and html. there are various options for how to tackle this, should not be a big problem.. 

## Associated Screenshots:
    
_( Welcome file extensions include gifs/png screenshots of your feature in action )_

- IF YOU HAVE ANY SCREENSHOTS, INCLUDE THEM HERE.
- IF YOU HAVE NO SCREENSHOTS, ENTER 'None'

### CODE REVIEW

**Review by NiallJoeMaher — APPROVED** [review]
Holy 💩 that's a lot of code! Thanks for this. I think we can get it merged and then worry about cleaning it up since it's hidden anyway.

**Comment by xiaoniuniu89** [comment]
I have some time tomorrow to fix it up if it is not deploying, just let me know what the problem is.

**Comment by xiaoniuniu89** [comment]
> Holy hankey that's a lot of code! Thanks for this. I think we can get it merged and then worry about cleaning it up since it's hidden anyway.

yea, this was a bear to code!!

**Comment by NiallJoeMaher** [comment]
> I have some time tomorrow to fix it up if it is not deploying, just let me know what the problem is.

Yes please! That way when we merge it won't hold up any builds.

**Comment by xiaoniuniu89** [comment]
will take a guess and say it is failing a lot of ts linting checks - I'll try fix them all over the weekend

**Comment by xiaoniuniu89** [comment]
can try deploy again please

**Pull request merged**
