### PR TITLE
Added mobile safari and desktop chrome to playwright test browsers

### PR DESCRIPTION
**Pull request by JohnAllenTech**
# ✨ Codu Pull Request 💻

Improves E2E testing overall. There are dozens of poor unfortunate souls using mobile safari. We should do everything we can to help their struggle.

## Pull Request details

- Added mobile safari as a test platform
- Added desktop firefox as a test platform

## Any Breaking changes

- None

## Associated Screenshots

image

### CODE REVIEW

**Review by NiallJoeMaher — APPROVED** [review]
🌮 🦖

**Comment by NiallJoeMaher** [comment]
Getting some errors in the playwright runner around bookmarks and algolia. Nice and strange 🤔

**Comment by JohnAllenTech** [comment]
> Getting some errors in the playwright runner around bookmarks and algolia. Nice and strange 🤔

Yeah I saw that. My guess was the mybookmarks endpoint is being called even if a user isnt logged in. Ill take a quick look tonight

**Comment by JohnAllenTech** [comment]
Created n issue for it #1138

**Pull request merged**
