### PR TITLE
docs: Create issue template

### LINKED ISSUE #52: Add issue templates
Open to suggested Issue templates.

### PR DESCRIPTION
**Pull request by VadimDez**
## Pull Request details:
- Create template for issues, closes #52

## Any Breaking changes:
None

## Associated Screenshots:
None

### CODE REVIEW

**Comment by pkspyder007** [comment]
@VadimDez Thanks for the PR, can you add a section for screenshot and additional info section in template.

@NiallJoeMaher Do you have any specific template in your mind...

**Comment by pkspyder007** [comment]
@VadimDez Thanks for the PR, can you add a section for screenshot and additional info section in template.

@NiallJoeMaher Do you have any specific template in your mind...

**Comment by VadimDez** [comment]
@pkspyder007 added Screenshots and Additional info sections

**Comment by VadimDez** [comment]
@pkspyder007 @NiallJoeMaher any feedback? Can this be merged?

**Comment by NiallJoeMaher** [comment]
Will get on this shortly! Sorry about the delay. Having my first holiday away from my laptop in about 8 years. 😂 💅

Going to grab some coffee and look over it.

**Review by NiallJoeMaher — APPROVED** [review]
This is perfect as a template to start so going to merge this. Thanks for the help! I'll be home on the weekend so your next PRs will get worked on much faster. ❤️

**Review by NiallJoeMaher — APPROVED** [review]

**Pull request merged**
