### PR TITLE
Add crypto import

### LINKED ISSUE #1048: Node version in package.json is 18.17.1 but db:seed script needs crypto from 20.x
## Context

Using node v18.18.0 seed script fails with

image

due to

```
 id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
```

in drizzle schema. 

## Expected Behavior

Seed script should run with node version specified in package.json

## Current Behavior

Seed script doesnt run with node version specified in package.json

## Screenshots

Drag and drop screenshots here to better describe your issue

## Steps to reproduce

Please provide detailed steps for reproducing the issue

1. Switch your node version to 18.x
2. run `npm run db:seed`

## Additional info

Could be a 1 liner. Maybe crypto was only added in v20 ?

### PR DESCRIPTION
**Pull request by CarolinaCobo**
# ✨ Codu Pull Request 💻

Fixes #(issue)

## Pull Request details

- Some people weren't able to run the `npm run db:seed` and getting this error `Error: ReferenceError: crypto is not defined` 
- Adding the import in the schema.ts file fixes this

### CODE REVIEW

**Comment by JohnAllenTech** [comment]
I cant see crypto in the package.json ?

Can you import crypto directly like this from Node V18 ?

**Comment by CarolinaCobo** [comment]
you don't need it on the package, if you add it on the server/db/schema.ts at the top it will work. I was talking to Niall about it and it works no problem in node 20 so we'll be updating that too

**Comment by JohnAllenTech** [comment]
> you don't need it on the package, if you add it on the server/db/schema.ts at the top it will work. I was talking to Niall about it and it works no problem in node 20 so we'll be updating that too

Really interesting! Is it bundled with Node v18?

Edit: Bot answered my question. Its bundled in Node versions >=14.17.0

**Review by NiallJoeMaher — APPROVED** [review]
🌮

**Pull request merged**
