### PR TITLE
chore: added all selected columns to the groupBy function

### LINKED ISSUE #1053: Articles page not working after seeding DB
## Context

After following README article page doesnt work locally

`❌ tRPC failed on post.published: column "Post.slug" must appear in the GROUP BY clause or be used in an aggregate function
 GET /api/trpc/post.published,tag.get?batch=1&input=%7B%220%22%3A%7B%22json%22%3A%7B%22limit%22%3A15%2C%22sort%22%3A%22newest%22%2C%22tag%22%3Anull%2C%22cursor%22%3Anull%7D%2C%22meta%22%3A%7B%22values%22%3A%7B%22cursor%22%3A%5B%22undefined%22%5D%7D%7D%7D%2C%221%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D 200 in 1455ms`

## Expected Behavior

Article page working

## Current Behavior

Article page not working

## Screenshots

Article page not displaying correctly
## Steps to reproduce

Please provide detailed steps for reproducing the issue

1. npm run db:nuke
2. npm run db:push
3. npm run db:seed
4. npm run dev
5. Navigate to http://localhost:3000/articles and youll see below

## Additional info

Provide any additional information here

### PR DESCRIPTION
**Pull request by JohnAllenTech**
# ✨ Codu Pull Request 💻

Fixes #1053

## Pull Request details

Seems like a new thing in drizzle? Didnt try to revert versions just fixed it in place.

## Any Breaking changes

- Potentially. I will need help to test this. Seems to work locally but need a second set of eyes before Id be confident to merge

## Associated Screenshots

image

### CODE REVIEW

**Comment by NiallJoeMaher** [comment]
Should we bump drizzle to the latest version to see what it breaks in this too (that's coming in a PR anyway 😂 )

**Comment by JohnAllenTech** [comment]
> Should we bump drizzle to the latest version to see what it breaks in this too (that's coming in a PR anyway 😂 )

Will do

**Comment by JohnAllenTech** [comment]
@NiallJoeMaher bumped the dependency and everything is still working.

**Review by NiallJoeMaher — APPROVED** [review]
🌮

**Pull request merged**
