### PR TITLE
Added Drizzle to README.md

### PR DESCRIPTION
**Pull request by leslyclopez11**
# ✨ Codu Pull Request 💻

Fixes #1033

## Pull Request details

- Added Drizzle link to README.dm

### CODE REVIEW

**Comment by NiallJoeMaher** [comment]
Hey @leslyclopez11! Thanks for this. Would you update the PR template? You'll see that it has `Fixes #(issue)`, which should take the issue number that you took (1030). Also just adding some PR details like in the template. 

You can delete the Any Breaking changes and Associated Screenshots sections as they aren't needed for this PR.

**Comment by John-Paul-Larkin** [comment]
Hey @leslyclopez11,

Thanks for this PR. You are almost there with your first contribution. 🥳  
Can you please edit the PR to fill in the details Niall suggested. It may seem kind of pointless, but documentation provides clarity and and forms the foundation of any great project.

**Comment by leslyclopez11** [comment]
@John-Paul-Larkin @NiallJoeMaher sorry for taking so long to answer! I updated the PR details. Let me know if there is anything else I have to do!

**Review by John-Paul-Larkin — APPROVED** [review]

**Comment by John-Paul-Larkin** [comment]
🥳 
Congrats on your first PR leslyclopez11.

PS Do you have a Linkedin profile you can share?

**Comment by leslyclopez11** [comment]
@John-Paul-Larkin Omg, thank you so much! Yes, this is my LinkedIn: https://www.linkedin.com/in/lesly-catota-lopez-9a5110256

**Pull request merged**
