### PR TITLE
feat: init e2e workflow setup

### PR DESCRIPTION
**Pull request by pkspyder007**
# ✨ Codu Pull Request 💻

Fixes #(issue)
- NA

## Pull Request details

- Created a workflow to run e2e tests under e2e env with pre-seeded db and github app setup 
- Requires few secrets to to added for db and github app setup

## Any Breaking changes

- None

## Associated Screenshots

- None

### CODE REVIEW

**Comment by pkspyder007** [comment]
The tests will start passing once [this PR ](https://github.com/codu-code/codu/pull/1085)merged and rebased into the e2e workflow branched

**Comment by pkspyder007** [comment]
@NiallJoeMaher @John-Paul-Larkin 
I am not having access to add secrets to the repo, if any of you could create a new supabase instance and add the 
`E2E_DATABASE_URL` in the secret we'll have a persistent E2E DB

Also we need to create github oauth client for testing github auth flows
That will require similar secrets please refer to the workflow implementaion

**Comment by NiallJoeMaher** [comment]
@pkspyder007 - Do you think we should use an e2e database url or just give it a database URL it can use instead (rather than having a separate one). Eg. if we used `DATABASE_URL` would there be any issue?

**Comment by pkspyder007** [comment]
> @pkspyder007 - Do you think we should use an e2e database url or just give it a database URL it can use instead (rather than having a separate one). Eg. if we used `DATABASE_URL` would there be any issue?

@NiallJoeMaher The current setup uses `DATABASE_URL` only I have just named secret to have E2E in the name so its clear to understand what this DB url exactly is.
Our `E2E_DATABASE_URL` will contain link to a postgres db with seeded data.

**Comment by pkspyder007** [comment]
Also wanna add that running a docker image will utilise more resource and cost us more and lead to increased the CI times.

**Comment by praveen-quizizz** [comment]
@NiallJoeMaher have a look whenever you get time

few action items
- check for login test flakiness
- fix seeding
- updating and revamping skipped tests
- move tests results to report on PR and host traces to something like S3

**Review by NiallJoeMaher — APPROVED** [review]
🌮

**Pull request merged**
