### PR TITLE
Fixed ProgressBar

### LINKED ISSUE #551: Fix the progress bar for when screens are loading
## Context

Currently, on www.codu.co, we get a progress bar when changing pages.
With the new `next/navigation` package, the way we handled this no longer works.
I'm open to suggestions that might help us fix this and show the loading indicator so the site doesn't feel laggy. 

You can find this component in `components/ProgressBar/ProgressBar.tsx`.
You'll see it is commented out on `app/layout.tsx`.

## Expected Behavior

Expecting the progress bar to work as it currently does but if not possible that suggestions are offered and agreed and implemented. 

## Current Behavior

We commented out the progress bar for the moment. 

## Screenshots

https://github.com/codu-code/codu/assets/12615742/7d519fec-454b-4c79-9e4f-cdaaaaa80712

### PR DESCRIPTION
**Pull request by seog-jun**
Fixes #551 
# ✨ Codu Pull Request 💻

Codu Logo

👉 _**Please remove the below and replace with your own values, leaving the headers where they are.**_ 👈

## Pull Request details:
- Used `NextTopLoader` component as the current `ProgressBar` component is broke(`Next.js 13` doesn't support `router.events.on/off` anymore)
- Added a new `CSS gradient` to apply the gradient to `NextTopLoader`

## Any Breaking changes:
- None

## Associated Screenshots:
 

https://github.com/codu-code/codu/assets/88434287/6cf8aae9-efeb-4cb4-b482-130f514efffd

### CODE REVIEW

**Comment by NiallJoeMaher** [comment]
Do you have any ideas on why when I go to the homepage, it doesn't do the full animation? 

The other pages seem to be fine. 🤔 

https://github.com/codu-code/codu/assets/12615742/17626039-41ff-46d9-9c84-465502d3a576

**Comment by seog-jun** [comment]
@NiallJoeMaher Well, I don't really see that issue from my end, but I put the `linear` for the same speed when loading. Please let me know if you still can see the issue. 

https://github.com/codu-code/codu/assets/88434287/3afdfb40-7e62-4721-9736-85bd6d15d775

**Review by NiallJoeMaher — CHANGES_REQUESTED** [review]
Could you remove the unused progress bar and package if we no longer are using it? Thanks! 🌮

**Comment by seog-jun** [comment]
@NiallJoeMaher For sure!

**Comment by seog-jun** [comment]
@NiallJoeMaher Could you please review the PR again? I'd appreciate that!

**Review by NiallJoeMaher — APPROVED** [review]
Great work!

**Pull request merged**
