### PR TITLE
Migrating community calls from Prisma to Drizzle

### PR DESCRIPTION
**Pull request by JohnAllenTech**
# ✨ Codu Pull Request 💻

Codu Logo

## Pull Request details

Alt Text

## Any Breaking changes

- None

## Associated Screenshots

image

## Summary by CodeRabbit

- **Performance Improvements**
	- Reduced the default limit for community queries to enhance load times.
- **Enhancements**
	- Updated community fetching logic to better handle filters and pagination.
	- Improved the handling and updating of community data and memberships.
- **Refactor**
	- Streamlined community creation and membership association processes.

### CODE REVIEW

**Review by NiallJoeMaher — APPROVED** [review]
🌮 LGTM!

**Comment by NiallJoeMaher** [comment]
Build is broken 😢

**Comment by JohnAllenTech** [comment]
> Build is broken 😢 

Will sort it tonight. Reckon there's an issue with my prettier as having issues on other projects

**Comment by JohnAllenTech** [comment]
> Build is broken 😢

I cant replicate this locally


https://github.com/codu-code/codu/assets/46611809/ecaa3343-daa9-4713-98ad-27d419e71f0f

Can we give it the old on/off please

**Pull request merged**
