### PR TITLE
MVP Events & Communities

### PR DESCRIPTION
**Pull request by remojansen**
## Pull Request details:
MVP support for creating events and communities so Codu can replace meetup.com

## Any Breaking changes:
Everything should continue to work, but the user profile page now has more sections

## Associated Screenshots:
https://gist.github.com/remojansen/68ff63f9024f9f952683731c12537bc9

✅ Hacktoberfest

### CODE REVIEW

**Comment by remojansen** [comment]
This is MVP, here are some things that should be done in the future:

- SEO Metadata
- Event comments
- Add lat & long to events + filter by geolocation
- Event flags hybrid, in-person, online
- Add event to calendar
- Share events on social media
- Add event co-organisers
- +1 attendees
- Event checking in

**Comment by NiallJoeMaher** [comment]
This is a mighty amount of work! It'll take a couple of days to review/test it all. Thanks for all the awesome work.

**Comment by remojansen** [comment]
Here are the actions and business rules it might help you while testing it:

- Create a community --> Button on the communities home page (needs a session)
- Edit a community -->  Button on community home page  (needs a session + being one of the community organisers)
- Create an event -->   Button on community home page  (needs a session + being one of the community organisers)
- Edit an event -->  Button on event home page  (needs a session + being one of the community organisers)
- Join community --> Button on community home page (needs a session + NOT being one of the community organisers)
- Leave community -->  Button on community home page (needs a session + NOT being one of the community organisers)
- RSVP --> Button on event home page  (needs a session + NOT being one of the community organisers)
    -  If the capacity is reached, the RSVP is displayed in the waiting list automatically
- Cancel RSVP --> Button on event home page  (needs a session + NOT being one of the community organisers)

I left the following out:

- Draft events: In meetup.com, it is common to announce a meetup and say something like talks TBD, so I left this out for simplicity.
- Delete event: I left this out because I don't have admin knowledge. I thought that it would be better if you implemented this feature.
- Delete community: I left this out for the same reasons as the previous ones and because deleting an event could be bad for the codu platform. In meetup, for example events are not deleted, and someone else can become the new organiser.

One last thing: I went to the preview site, but looks like the data migration is not applied there:

Screenshot 2023-11-04 at 09 30 47

**Comment by praveen-quizizz** [comment]
Just a thought, what if we break this big PR into smaller feature request pr.
That might make it easier to go through
@NiallJoeMaher @remojansen

**Comment by NiallJoeMaher** [comment]
> Just a thought, what if we break this big PR into smaller feature request pr.
> 
> That might make it easier to go through
> 
> @NiallJoeMaher @remojansen 

Thanks for the suggestion! On this occasion I'm happy enough because I've chatted with Reno separately about this feature and he's no amateur with this stuff. 🦾

**Review by NiallJoeMaher — APPROVED** [review]
Very cool! Really excited to have this in the app. 🦾

**Pull request merged**
