### PR TITLE
chore: replace img with next imgs in static pages

### PR DESCRIPTION
**Pull request by DogPawHat**
Lotta linter warnings about this, so gonna give this a shot.

### CODE REVIEW

**Comment by NiallJoeMaher** [comment]
I'm gonna test this branch! I know that dang Image tag can behave weirdly. That's why I didn't use it all straight away

**Comment by NiallJoeMaher** [comment]
Yup as I suspected, this throws a few warnings/errors
Screenshot 2022-08-01 at 19 22 25

**Comment by DogPawHat** [comment]
Ah ok, it's not happy if you just use tailwind classes then ☹️

**Comment by NiallJoeMaher** [comment]
@DogPawHat yes! Let's close it unless we can figure out a way of making it work. Or we can revisit later. 🦾

**Pull request closed without merging**
