### PR TITLE
Removed view preview button with its associated code

### LINKED ISSUE #1022: Meta issue : Editor
## Context

Codu currently uses a Markdown editor for creating posts. [Current editor](https://www.codu.co/create)
[What is markdown?](https://www.markdownguide.org/getting-started/)

A new editor, currently a work in progress, is available in the alpha section of the site. This is not accessible in production, but you can use it in development by navigating to:
http://localhost:3000/alpha/new

It implements the [TipTap headless editor](https://tiptap.dev/), which is a rich text editor that's customisable and extendable through extensions. Its headless nature means it comes without a set user interface, so we can include and customise the features as we see fit.

## What changes would we like to implement? 
We would like to switch to a WYSIWYG rich text editor with a simpler interface and feature set.
[What is WYSIWYG?](https://en.wikipedia.org/wiki/WYSIWYG)
We are taking inspiration from editors implemented in medium/notion. Check those out for the kind of feel we are hoping to achieve.

The user should be able to make edits, with changes instantly reflected in the document as it would appear in its final state.

We will still include some basic markdown features, however most will be removed.
Expected markdown features (If practicable )
H2                     ##
H3                    ### 
Bullet points    *
Codeblocks      ```
inline code.      `
Note: Added if practicable because we will need to investigate how we can implement this through TipTap.

Rich text with certain actions available through a / slash menu or tooltip on hightlighting specific text. This already exists, however we would like to edit it to specific features.

## Connected issues

Remove toolbar from the alpha editor #1028
Editor Title is too verbose #1038
Auto-apply markdown features: Enable WYSIWYG #1039
~~Remove the preview button to make editor WYSIWYG #1024~~

...more Incoming

## Screenshots

Alpha editor in its current form.

New editor in alpha section

### PR DESCRIPTION
**Pull request by Prakhar29Sharma**
# ✨ Codu Pull Request 💻

Fixes #1022 

## Pull Request details

- Removed button element from app>(app)>alpha>new
- Removed state variable (viewPreview, setViewPreview) that was being changed when button was clicked using onClick()
- Removed code that was being rendered when viewPreview was set to true

## Any Breaking changes

- I removed viewPreview and setViewPreview from hooks/useCreatePage.ts, I'm not sure if it'll cause any issue  
- I was not able to test the changes properly as I was having issues with setting up codu in my local dev environment

## Associated Screenshots

- 'None'

### CODE REVIEW

**Comment by John-Paul-Larkin** [comment]
The PR looks good.
However I got a linting error. Simple fix. Just run the following script.
Thanks

`npm run prettier:fix`

**Comment by Prakhar29Sharma** [comment]
Hey @John-Paul-Larkin
Thanks for the feedback, I've fixed the linting error by running the given script. If there's anything else let me know.

**Review by John-Paul-Larkin — APPROVED** [review]

**Comment by NiallJoeMaher** [comment]
Nice one @Prakhar29Sharma! Thanks

**Comment by John-Paul-Larkin** [comment]
> Hey @John-Paul-Larkin Thanks for the feedback, I've fixed the linting error by running the given script. If there's anything else let me know.

Great work Prakhar29Sharma.
Congratulations on your first contribution to open source. 🥳

**Pull request merged**
