### PR TITLE
Add Enhancement(promptService): add prompt if user has unsaved change…

### PR DESCRIPTION
**Pull request by xiaoniuniu89**
…s and tries to naivgate from create page

# ✨ Codu Pull Request 💻

Codu Logo

👉 _**Please remove the below and replace with your own values, leaving the headers where they are.**_ 👈

## Pull Request details:
- Prompts user if they have unsaved changes and try to navigate away from Create/Editing a post. Trying to reuse Modal component. Would be nice to make further changes and refactor in the future to create a reusable component for all prompts eg: deleting a post. Pass in title, type message body, buttons etc. Page refresh not addressed yet. PLEASE QA BEFORE MERGING!

## Any Breaking changes:
None

## Associated Screenshots:
    
_( Welcome file extensions include gifs/png screenshots of your feature in action )_

None

### CODE REVIEW

**Comment by NiallJoeMaher** [comment]
Build is failing. 😢  

Screenshot 2023-02-11 at 11 09 43

It might take a day or two for me to review this while I'm travelling so sorry in advance for the delay!

**Comment by xiaoniuniu89** [comment]
im sorry, looks like a typo in the import statement, I have no idea how I changed that when pushing changes, will update later today!

**Review by NiallJoeMaher — CHANGES_REQUESTED** [review]
Looks great! That will come in useful in a lot of other places too. 

One small thing this is probably unwanted behaviour:

https://user-images.githubusercontent.com/12615742/220763015-38957b88-1e87-40a8-9540-65286283ac9f.mov

If a user comes back, the page saves (which will publish updates) which might not be intended. 

So I guess the user updating the article should only be by manually pressing the save button. 

Thanks for this btw! 

Runs really nicely. 🦾

**Comment by NiallJoeMaher** [comment]
Also, sorry about the major delay! I was away for a couple of weeks and hoped someone else would have the chance to look. 😢

**Comment by xiaoniuniu89** [comment]
No worries, will look at this at the weekend!!

**Review by NiallJoeMaher — APPROVED** [review]
LGTM! Thank you ❤️

**Pull request merged**
