### PR TITLE
feat: switch from Date to Temporal

### PR DESCRIPTION
**Pull request by DogPawHat**
https://tc39.es/proposal-temporal/docs/

ran into some cases where the server hydration would break because of a difference in locale between server and client. Proper fix is to restrict it to client side only, but for now I'll hardcode it to `en-IE`, and ditch the useless Date for the glorious if still in Stage 3 Temporal.

### CODE REVIEW

**Comment by NiallJoeMaher** [comment]
This is very cool! I didn't even know it was an issue. I need to do some reading on this Temporal stuff. 🤔

**Comment by NiallJoeMaher** [comment]
> https://tc39.es/proposal-temporal/docs/


This is very cool! I didn't even know it was an issue. I need to do some reading on this Temporal stuff. 🤔

**Comment by DogPawHat** [comment]
It's the future of time itself in JS. Currently it's blocked by the IETF needing to standardize an extension to RFC3339/ISO8601https://github.com/tc39/proposal-temporal/issues/1450

**Review by NiallJoeMaher — APPROVED** [review]
🌮 Cool thing to learn about! Cheers dude

**Pull request merged**
