### PR TITLE
fix: change next version to 13.5.0

### PR DESCRIPTION
**Pull request by Snowfall22**
# ✨ Codu Pull Request 💻

Codu Logo
Addresses issue #447  

## Pull Request details:
- Changed Next version to 13.5.0

## Any Breaking changes:
- None

## Associated Screenshots:
    
Screenshot 2023-10-01 150808

### CODE REVIEW

**Review by NiallJoeMaher — CHANGES_REQUESTED** [review]
Is it possible to update this to the latest version (because it includes bugfixes): `13.5.3`

**Comment by Snowfall22** [comment]
sure will do

**Comment by Snowfall22** [comment]
Next's version is now 13.5.3 @NiallJoeMaher 
Screenshot 2023-10-01 154230

**Review by NiallJoeMaher — APPROVED** [review]
LGTM! 🌮 Thanks

**Pull request merged**
