### PR TITLE
Post editor

### PR DESCRIPTION
**Pull request by patrickhladun**
# ✨ Codu Pull Request 💻

Codu Logo

## Pull Request details:
Issue #183 was created to improve the Save notification and make it less distracting. This feature aims to try an alternative design for the article editor. 

The Save notification is coded with the toaster component. When the post is saved automatically, it pops up from the top and disappears. There are options to set a different location for the notification, but this doesn't help much.

Screenshot 2023-04-21 at 16 45 50

The "Save" notification must be more subtle to not distract the user every few seconds when the article is auto-saved.

We have the Saved information and publish button at the bottom of the editor. So removing the toaster "Save" notification helps, and you still have Saved info on the bottom of the editor.

Screenshot 2023-04-21 at 16 46 45

But ideally, I would like to have this visible while I scroll up and down my article when writing it. To fix this, I removed the Publish button from the bottom of the editor and moved it to the top of that page in a top bar that sticks to the top when scrolling. This way publish button and Saved info will always be available.

I have added a Preview button to the top bar with an "Eye" icon.

I have removed sidebars and borders from the editor. Then I have added EditorHints component that adds "How to use the editor" at the bottom of the editor. This can be closed with "X" button but it will show again page is refreshed. Ideally, it would need to be added to the user settings so that when the user closes it, it will remain closed, and you could turn it on again in the settings or user dropdown menu.

I have added a new Layout component to remove the website footer from the article editor to make it even cleaner.

Here is a screenshot of how this could look with the editor action buttons in the header. The "Your posts" and "New Post" buttons could be put in the dropdown user menu instead and other website links removed.

Screenshot 2023-04-22 at 10 49 43

## Any Breaking changes:+
- None

### CODE REVIEW

**Comment by NiallJoeMaher** [comment]
@xiaoniuniu89 will any of these changes break anything for you? I know you are the only person actively working on this.

**Comment by NiallJoeMaher** [comment]
@patrickhladun some conflicts to clean up 😉

**Comment by xiaoniuniu89** [comment]
It looks good to me, can't see anything breaking!! but ..... we should definitely tackle testing soon!! Also maybe a story about refactoring some of the functionality into some separate modules. This page is getting hard to maintain!! This commit does a good job with that!! 

I can shoehorn some refactoring in while I am doing the editor!!

**Comment by patrickhladun** [comment]
@NiallJoeMaher Conflicts are resolved now.

**Review by NiallJoeMaher — APPROVED** [review]
LGTM! 🥳

**Pull request merged**
