### PR TITLE
Fix: Prevent article page from calling bookmarks for unauthenticated users (#1138)

### LINKED ISSUE #1138: Article page calling for bookmarks if if a user isnt logged in
## Context

Articles page is calling for bookmarks even when a user is not logged in.

This is causing errors in the console.

## Expected Behavior

Dont call for bookmarks if a user is not logged in

## Current Behavior

Calling for bookmarks when a user hasnt logged in

## Screenshots

image
## Steps to reproduce

Please provide detailed steps for reproducing the issue

1. Go to https://www.codu.co/articles
2. Look at console

image

## Additional info

Provide any additional information here

### PR DESCRIPTION
**Pull request by shanksxz**
# ✨ Codu Pull Request 💻

Fixes #1138 

## Pull Request details
- Prevents the article page from calling bookmarks when the user is not logged in, which was causing errors in the console.
- Updated the logic to only fetch bookmarks if a user is authenticated.
- Cleaned up the error messages caused by the unauthenticated bookmark requests.

## Any Breaking changes
- None

## Associated Screenshots
image

### CODE REVIEW

**Review by John-Paul-Larkin — APPROVED** [review]
This works great, thanks.

PS. @NiallJoeMaher 
Separately this has me wondering why this query is done in the ArticlePreview component?
The resulting data is not used here at all. 
The refetch is used when the user bookmarks an article, but this is definitely not the way to handle this.

**Comment by John-Paul-Larkin** [comment]
Hey @shanksxz 
Can you please run the prettier script, and commit the changes. Thanks.
npm run prettier:fix

**Comment by John-Paul-Larkin** [comment]
Hey @shanksxz 
Can you please run the prettier script, and commit the changes. Thanks.
npm run prettier:fix

**Review by John-Paul-Larkin — DISMISSED** [review]
Hey @shanksxz 
Can you please run the prettier script, and commit the changes. Thanks.
npm run prettier:fix

**Comment by shanksxz** [comment]
> This works great, thanks.
> 
> PS. @NiallJoeMaher Separately this has me wondering why this query is done in the ArticlePreview component? The resulting data is not used here at all. The refetch is used when the user bookmarks an article, but this is definitely not the way to handle this.

yeah true

**Comment by shanksxz** [comment]
> Hey @shanksxz Can you please run the prettier script, and commit the changes. Thanks. npm run prettier:fix

sure.

**Comment by JohnAllenTech** [comment]
Before this change
image
After this change
image

Love to see it

**Review by NiallJoeMaher — APPROVED** [review]

**Pull request merged**
