### PR TITLE
chore: moving out user auth out into a util for E2E tests

### PR DESCRIPTION
**Pull request by JohnAllenTech**
# ✨ Codu Pull Request 💻

Helps with #1168 and #468 

## Pull Request details

So eventually we will need multiple user personas in a single E2E test.

One example is a user replying to another users comment. This PR is a first step to support multiple users in our E2E test. Follow on PRs will create a new loggedInAsUserTwo function which will be used to reply to 'user on'

I have also switched from having our tests run as authenticated by default

## Any Breaking changes

- None

## Associated Screenshots

- None

### CODE REVIEW

**Review by NiallJoeMaher — DISMISSED** [review]

**Comment by JohnAllenTech** [comment]
Something strange happening when deployed. Will do some troubleshooting. Everything is working locally with the same commands.

**Comment by JohnAllenTech** [comment]
@NiallJoeMaher it seems that the PR workflow always runs from the main branches version.

I have a new env var thats needed for the tests to pass. Not sure how to work around this..

I am pretty confident it will pass the E2E tests if you merge it though. Can we see and revert if thats not the case?

**Comment by JohnAllenTech** [comment]
image
Heres the reason its failing.

It needs E2E_USER_ONE_SESSION_ID which i have added to the E2E test workflow file.

**Review by NiallJoeMaher — APPROVED** [review]
YOLO

**Comment by JohnAllenTech** [comment]
It worked anyway! I imagine this will be the same for the other two... maybe

**Pull request merged**
